// Code generated by goyacc -p grc -o internal/parse/parser.go internal/parse/parser.y. DO NOT EDIT.

//line internal/parse/parser.y:14
package parse

import __yyfmt__ "fmt"

//line internal/parse/parser.y:14

var parseResult *Node

var lastword int

//line internal/parse/parser.y:20
type grcSymType struct {
	yys  int
	node *Node
}

const ANDAND = 57346
const BACKBACK = 57347
const BANG = 57348
const CASE = 57349
const COUNT = 57350
const DUP = 57351
const ELSE = 57352
const END = 57353
const FLAT = 57354
const FN = 57355
const FOR = 57356
const IF = 57357
const IN = 57358
const OROR = 57359
const PIPE = 57360
const REDIR = 57361
const SREDIR = 57362
const SUB = 57363
const SUBSHELL = 57364
const SWITCH = 57365
const TWIDDLE = 57366
const WHILE = 57367
const WORD = 57368
const HUH = 57369
const PREDIR = 57370

var grcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ANDAND",
	"BACKBACK",
	"BANG",
	"CASE",
	"COUNT",
	"DUP",
	"ELSE",
	"END",
	"FLAT",
	"FN",
	"FOR",
	"IF",
	"IN",
	"OROR",
	"PIPE",
	"REDIR",
	"SREDIR",
	"SUB",
	"SUBSHELL",
	"SWITCH",
	"TWIDDLE",
	"WHILE",
	"WORD",
	"HUH",
	"'^'",
	"'='",
	"')'",
	"'\\n'",
	"PREDIR",
	"'$'",
	"';'",
	"'&'",
	"'{'",
	"'}'",
	"'('",
	"'`'",
}

var grcStatenames = [...]string{}

const grcEofCode = 1
const grcErrCode = 2
const grcInitialStackSize = 16

//line internal/parse/parser.y:120

//line yacctab:1
var grcExca = [...]int8{
	-1, 0,
	4, 29,
	11, 29,
	17, 29,
	18, 29,
	31, 29,
	34, 29,
	35, 29,
	-2, 0,
	-1, 1,
	1, -1,
	-2, 0,
}

const grcPrivate = 57344

const grcLast = 620

var grcAct = [...]uint8{
	63, 23, 59, 77, 55, 41, 23, 48, 144, 45,
	76, 4, 46, 150, 23, 23, 4, 62, 119, 109,
	23, 19, 75, 141, 51, 52, 108, 125, 128, 7,
	13, 124, 91, 32, 108, 50, 112, 39, 42, 108,
	104, 126, 84, 85, 86, 87, 23, 44, 94, 61,
	64, 80, 132, 33, 23, 23, 20, 88, 47, 60,
	106, 37, 79, 83, 101, 102, 43, 22, 96, 89,
	57, 92, 93, 42, 38, 39, 107, 95, 23, 31,
	98, 122, 6, 34, 79, 103, 90, 97, 61, 99,
	100, 18, 23, 23, 23, 2, 23, 105, 60, 23,
	111, 40, 118, 120, 121, 129, 123, 114, 37, 127,
	37, 80, 49, 146, 133, 14, 1, 131, 0, 113,
	0, 38, 39, 38, 39, 0, 130, 0, 53, 54,
	134, 117, 78, 5, 0, 0, 23, 110, 5, 23,
	35, 36, 23, 0, 23, 147, 140, 23, 23, 142,
	147, 147, 145, 153, 149, 151, 152, 145, 145, 135,
	0, 136, 0, 0, 0, 0, 138, 28, 73, 71,
	25, 20, 143, 0, 26, 70, 65, 68, 66, 0,
	0, 21, 22, 0, 74, 69, 72, 67, 30, 0,
	58, 56, 0, 0, 0, 24, 28, 73, 71, 25,
	29, 27, 0, 26, 70, 65, 68, 66, 0, 0,
	81, 0, 0, 74, 69, 72, 67, 30, 0, 0,
	82, 0, 155, 37, 24, 154, 0, 0, 0, 29,
	27, 28, 73, 71, 25, 0, 38, 39, 26, 70,
	65, 68, 66, 0, 0, 81, 0, 0, 74, 69,
	72, 67, 30, 35, 36, 82, 115, 116, 0, 24,
	28, 73, 71, 25, 29, 27, 0, 26, 70, 65,
	68, 66, 0, 0, 81, 0, 0, 74, 69, 72,
	67, 30, 0, 108, 82, 0, 0, 0, 24, 0,
	0, 19, 0, 29, 27, 28, 73, 71, 25, 20,
	0, 0, 26, 70, 65, 68, 66, 0, 0, 21,
	22, 0, 74, 69, 72, 67, 30, 0, 0, 82,
	0, 0, 0, 24, 0, 0, 0, 0, 29, 27,
	28, 15, 148, 25, 20, 0, 0, 26, 17, 9,
	8, 0, 0, 0, 21, 22, 0, 16, 11, 12,
	10, 30, 0, 0, 0, 0, 0, 0, 24, 0,
	0, 19, 0, 29, 27, 28, 15, 0, 25, 20,
	0, 0, 26, 17, 9, 8, 0, 0, 0, 21,
	22, 0, 16, 11, 12, 10, 30, 0, 0, 0,
	0, 119, 0, 24, 0, 0, 19, 0, 29, 27,
	28, 73, 71, 25, 0, 0, 0, 26, 70, 65,
	68, 66, 0, 0, 81, 0, 0, 74, 69, 72,
	67, 30, 0, 0, 82, 139, 0, 0, 24, 28,
	73, 71, 25, 29, 27, 0, 26, 70, 65, 68,
	66, 0, 0, 81, 0, 0, 74, 69, 72, 67,
	30, 0, 0, 82, 137, 0, 0, 24, 28, 73,
	71, 25, 29, 27, 0, 26, 70, 65, 68, 66,
	0, 0, 81, 0, 0, 74, 69, 72, 67, 30,
	0, 0, 82, 0, 0, 0, 24, 0, 0, 19,
	3, 29, 27, 28, 15, 0, 25, 20, 0, 0,
	26, 17, 9, 8, 0, 0, 0, 21, 22, 0,
	16, 11, 12, 10, 30, 0, 0, 0, 0, 0,
	0, 24, 0, 0, 19, 0, 29, 27, 28, 73,
	71, 25, 0, 0, 0, 26, 70, 65, 68, 66,
	0, 0, 81, 0, 0, 74, 69, 72, 67, 30,
	28, 15, 82, 25, 20, 0, 24, 26, 17, 9,
	8, 29, 27, 0, 21, 22, 0, 16, 11, 12,
	10, 30, 0, 0, 0, 0, 0, 0, 24, 0,
	0, 19, 0, 29, 27, 28, 73, 71, 25, 0,
	0, 0, 26, 70, 65, 68, 66, 0, 0, 81,
	0, 0, 74, 69, 72, 67, 30, 0, 0, 0,
	0, 0, 0, 24, 0, 0, 0, 0, 29, 27,
}

var grcPact = [...]int16{
	488, -1000, 22, 22, 219, 545, -1000, 47, -29, -26,
	-29, -31, 7, 545, 545, 7, 7, -1000, 162, 545,
	-1000, 453, 523, -1000, 523, 523, 523, 453, 523, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 47, 523, -1000, 545, 523, -1000, 523, 523,
	-1000, -1000, 19, 545, 545, 453, 580, 290, 523, -1000,
	6, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -18, 106, 545, -1000, 6,
	-1000, -15, -1000, 6, 15, -1000, -1000, -1000, -1000, 255,
	226, 360, 360, 360, -1000, 360, 1, 11, 360, -2,
	6, 19, 19, -1000, 6, 6, -1000, -1000, 523, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 6, 19, -1000,
	19, -1000, -1000, 104, -1000, -1000, -1000, 57, -1000, 523,
	-1000, 424, -1000, -1000, 395, 360, -13, -1000, 360, -1000,
	57, 325, 57, 360, -24, 106, 325, 325, -1000, 57,
	-1000, -1000, -1000, 191, -1000, -1000,
}

var grcPgo = [...]uint8{
	0, 116, 115, 22, 29, 113, 8, 10, 132, 3,
	0, 5, 91, 95, 86, 47, 30, 17, 82, 81,
	40, 4, 2, 70, 52, 50, 79, 32, 112,
}

var grcR1 = [...]int8{
	0, 1, 1, 26, 26, 8, 8, 13, 13, 3,
	3, 9, 9, 4, 15, 2, 11, 11, 16, 16,
	16, 5, 5, 6, 6, 6, 19, 24, 24, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 28, 28, 18,
	18, 23, 23, 22, 22, 12, 12, 17, 17, 20,
	20, 10, 10, 10, 10, 10, 10, 10, 10, 10,
	10, 10, 25, 25, 25, 25, 25, 25, 25, 25,
	25, 25, 25, 21, 21, 14, 14, 14, 27, 27,
}

var grcR2 = [...]int8{
	0, 2, 2, 1, 1, 2, 2, 1, 2, 1,
	2, 1, 2, 3, 3, 3, 0, 2, 1, 2,
	2, 3, 3, 1, 2, 2, 2, 0, 3, 0,
	1, 2, 4, 8, 6, 4, 8, 4, 4, 4,
	4, 2, 2, 3, 3, 3, 2, 0, 1, 1,
	2, 1, 2, 1, 1, 1, 3, 1, 1, 1,
	3, 2, 5, 2, 2, 2, 2, 3, 3, 3,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 0, 2, 0, 2, 2, 0, 2,
}

var grcChk = [...]int16{
	-1000, -1, -13, 2, -7, -8, -18, -4, 15, 14,
	25, 23, 24, -16, -2, 6, 22, 13, -12, 36,
	9, 19, 20, -10, 33, 8, 12, 39, 5, 38,
	26, -26, 11, 31, -26, 34, 35, 4, 17, 18,
	-13, -11, -16, 19, -15, 38, 38, -15, 38, -28,
	28, -7, -7, -28, -28, -21, 29, -23, 28, -22,
	-20, -16, -17, -10, -25, 14, 16, 25, 15, 23,
	13, 7, 24, 6, 22, -3, -7, -9, -8, -20,
	-4, 19, 29, -20, -17, -17, -17, -17, -4, -20,
	-14, -27, -27, -27, -11, -27, -3, -20, -27, -20,
	-20, -7, -7, -4, -20, -20, -22, -17, 28, 37,
	31, -3, 21, -4, -17, 30, 31, -20, -7, 31,
	-7, -7, -19, -7, 30, 16, 30, -7, 30, -21,
	-17, -21, -24, 10, -21, -27, -27, 30, -27, 30,
	-7, 36, -7, -27, -6, -7, -5, -9, 7, -7,
	37, -6, -6, -21, 34, 31,
}

var grcDef = [...]int8{
	-2, -2, 0, 0, 7, 29, 30, 16, 0, 0,
	0, 0, 47, 29, 29, 47, 47, 83, 49, 29,
	18, 0, 0, 55, 0, 0, 0, 0, 0, 85,
	71, 1, 3, 4, 2, 5, 6, 88, 88, 88,
	8, 31, 16, 0, 88, 29, 0, 88, 0, 0,
	48, 41, 42, 29, 29, 46, 82, 50, 0, 51,
	53, 54, 59, 57, 58, 72, 73, 74, 75, 76,
	77, 78, 79, 80, 81, 0, 9, 29, 11, 19,
	70, 0, 82, 20, 61, 63, 64, 65, 66, 0,
	0, 29, 29, 29, 17, 29, 0, 0, 29, 0,
	83, 43, 44, 45, 84, 15, 52, 56, 0, 13,
	12, 10, 83, 67, 68, 69, 86, 87, 38, 89,
	39, 40, 32, 27, 14, 83, 88, 35, 88, 37,
	60, 0, 26, 88, 0, 29, 0, 62, 29, 88,
	34, 29, 28, 29, 0, 23, 29, 29, 83, 33,
	36, 24, 25, 0, 21, 22,
}

var grcTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	31, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 33, 3, 35, 3,
	38, 30, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 34,
	3, 29, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 28, 3, 39, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 36, 3, 37,
}

var grcTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 32,
}

var grcTok3 = [...]int8{
	0,
}

var grcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	grcDebug        = 0
	grcErrorVerbose = false
)

type grcLexer interface {
	Lex(lval *grcSymType) int
	Error(s string)
}

type grcParser interface {
	Parse(grcLexer) int
	Lookahead() int
}

type grcParserImpl struct {
	lval  grcSymType
	stack [grcInitialStackSize]grcSymType
	char  int
}

func (p *grcParserImpl) Lookahead() int {
	return p.char
}

func grcNewParser() grcParser {
	return &grcParserImpl{}
}

const grcFlag = -1000

func grcTokname(c int) string {
	if c >= 1 && c-1 < len(grcToknames) {
		if grcToknames[c-1] != "" {
			return grcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func grcStatname(s int) string {
	if s >= 0 && s < len(grcStatenames) {
		if grcStatenames[s] != "" {
			return grcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func grcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !grcErrorVerbose {
		return "syntax error"
	}

	for _, e := range grcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + grcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(grcPact[state])
	for tok := TOKSTART; tok-1 < len(grcToknames); tok++ {
		if n := base + tok; n >= 0 && n < grcLast && int(grcChk[int(grcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if grcDef[state] == -2 {
		i := 0
		for grcExca[i] != -1 || int(grcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; grcExca[i] >= 0; i += 2 {
			tok := int(grcExca[i])
			if tok < TOKSTART || grcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if grcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += grcTokname(tok)
	}
	return res
}

func grclex1(lex grcLexer, lval *grcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(grcTok1[0])
		goto out
	}
	if char < len(grcTok1) {
		token = int(grcTok1[char])
		goto out
	}
	if char >= grcPrivate {
		if char < grcPrivate+len(grcTok2) {
			token = int(grcTok2[char-grcPrivate])
			goto out
		}
	}
	for i := 0; i < len(grcTok3); i += 2 {
		token = int(grcTok3[i+0])
		if token == char {
			token = int(grcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(grcTok2[1]) /* unknown char */
	}
	if grcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", grcTokname(token), uint(char))
	}
	return char, token
}

func grcParse(grclex grcLexer) int {
	return grcNewParser().Parse(grclex)
}

func (grcrcvr *grcParserImpl) Parse(grclex grcLexer) int {
	var grcn int
	var grcVAL grcSymType
	var grcDollar []grcSymType
	_ = grcDollar // silence set and not used
	grcS := grcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	grcstate := 0
	grcrcvr.char = -1
	grctoken := -1 // grcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		grcstate = -1
		grcrcvr.char = -1
		grctoken = -1
	}()
	grcp := -1
	goto grcstack

ret0:
	return 0

ret1:
	return 1

grcstack:
	/* put a state and value onto the stack */
	if grcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", grcTokname(grctoken), grcStatname(grcstate))
	}

	grcp++
	if grcp >= len(grcS) {
		nyys := make([]grcSymType, len(grcS)*2)
		copy(nyys, grcS)
		grcS = nyys
	}
	grcS[grcp] = grcVAL
	grcS[grcp].yys = grcstate

grcnewstate:
	grcn = int(grcPact[grcstate])
	if grcn <= grcFlag {
		goto grcdefault /* simple state */
	}
	if grcrcvr.char < 0 {
		grcrcvr.char, grctoken = grclex1(grclex, &grcrcvr.lval)
	}
	grcn += grctoken
	if grcn < 0 || grcn >= grcLast {
		goto grcdefault
	}
	grcn = int(grcAct[grcn])
	if int(grcChk[grcn]) == grctoken { /* valid shift */
		grcrcvr.char = -1
		grctoken = -1
		grcVAL = grcrcvr.lval
		grcstate = grcn
		if Errflag > 0 {
			Errflag--
		}
		goto grcstack
	}

grcdefault:
	/* default state action */
	grcn = int(grcDef[grcstate])
	if grcn == -2 {
		if grcrcvr.char < 0 {
			grcrcvr.char, grctoken = grclex1(grclex, &grcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if grcExca[xi+0] == -1 && int(grcExca[xi+1]) == grcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			grcn = int(grcExca[xi+0])
			if grcn < 0 || grcn == grctoken {
				break
			}
		}
		grcn = int(grcExca[xi+1])
		if grcn < 0 {
			goto ret0
		}
	}
	if grcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			grclex.Error(grcErrorMessage(grcstate, grctoken))
			Nerrs++
			if grcDebug >= 1 {
				__yyfmt__.Printf("%s", grcStatname(grcstate))
				__yyfmt__.Printf(" saw %s\n", grcTokname(grctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for grcp >= 0 {
				grcn = int(grcPact[grcS[grcp].yys]) + grcErrCode
				if grcn >= 0 && grcn < grcLast {
					grcstate = int(grcAct[grcn]) /* simulate a shift of "error" */
					if int(grcChk[grcstate]) == grcErrCode {
						goto grcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if grcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", grcS[grcp].yys)
				}
				grcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if grcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", grcTokname(grctoken))
			}
			if grctoken == grcEofCode {
				goto ret1
			}
			grcrcvr.char = -1
			grctoken = -1
			goto grcnewstate /* try again in the same state */
		}
	}

	/* reduction by production grcn */
	if grcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", grcn, grcStatname(grcstate))
	}

	grcnt := grcn
	grcpt := grcp
	_ = grcpt // guard against "declared and not used"

	grcp -= int(grcR2[grcn])
	// grcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if grcp+1 >= len(grcS) {
		nyys := make([]grcSymType, len(grcS)*2)
		copy(nyys, grcS)
		grcS = nyys
	}
	grcVAL = grcS[grcp+1]

	/* consult goto table to find next state */
	grcn = int(grcR1[grcn])
	grcg := int(grcPgo[grcn])
	grcj := grcg + grcS[grcp].yys + 1

	if grcj >= grcLast {
		grcstate = int(grcAct[grcg])
	} else {
		grcstate = int(grcAct[grcj])
		if int(grcChk[grcstate]) != -grcn {
			grcstate = int(grcAct[grcg])
		}
	}
	// dummy call; replaced with literal code
	switch grcnt {

	case 1:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:28
		{
			grcVAL.node = grcDollar[1].node
			parseResult = grcVAL.node
			return 1
		}
	case 2:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:29
		{
			parseResult = nil
			return 1
		}
	case 6:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:33
		{
			grcVAL.node = N(KBg, grcDollar[1].node, nil)
		}
	case 8:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:35
		{
			grcVAL.node = N(KSeq, grcDollar[1].node, grcDollar[2].node)
		}
	case 10:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:37
		{
			grcVAL.node = N(KSeq, grcDollar[1].node, grcDollar[2].node)
		}
	case 12:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:39
		{
			grcVAL.node = grcDollar[1].node
		}
	case 13:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:40
		{
			grcVAL.node = N(KBrace, grcDollar[2].node, nil)
		}
	case 14:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:41
		{
			grcVAL.node = N(KParen, grcDollar[2].node, nil)
		}
	case 15:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:42
		{
			grcVAL.node = N(KAssign, grcDollar[1].node, grcDollar[3].node)
		}
	case 16:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:43
		{
			grcVAL.node = nil
		}
	case 17:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:44
		{
			grcVAL.node = L(KRedir, grcDollar[1].node, grcDollar[2].node)
		}
	case 18:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:45
		{
			grcVAL.node = grcDollar[1].node
		}
	case 19:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:46
		{
			grcVAL.node = grcDollar[1].node
			grcVAL.node.Right = grcDollar[2].node
		}
	case 20:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:47
		{
			grcVAL.node = grcDollar[1].node
			grcVAL.node.Right = grcDollar[2].node
		}
	case 21:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:48
		{
			grcVAL.node = N(KCase, grcDollar[2].node, nil)
		}
	case 22:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:49
		{
			grcVAL.node = N(KCase, grcDollar[2].node, nil)
		}
	case 23:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:50
		{
			grcVAL.node = N(KCbody, grcDollar[1].node, nil)
		}
	case 24:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:51
		{
			grcVAL.node = N(KCbody, grcDollar[1].node, grcDollar[2].node)
		}
	case 25:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:52
		{
			grcVAL.node = N(KCbody, grcDollar[1].node, grcDollar[2].node)
		}
	case 26:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:53
		{
			if grcDollar[2].node != nil {
				grcVAL.node = N(KElse, grcDollar[1].node, grcDollar[2].node)
			} else {
				grcVAL.node = grcDollar[1].node
			}
		}
	case 27:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:54
		{
			grcVAL.node = nil
		}
	case 28:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:55
		{
			grcVAL.node = grcDollar[3].node
		}
	case 29:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:56
		{
			grcVAL.node = nil
		}
	case 30:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:57
		{
			grcVAL.node = buildCallFromSimple(grcDollar[1].node)
		}
	case 31:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:58
		{
			grcVAL.node = N(KBrace, grcDollar[1].node, grcDollar[2].node)
		}
	case 32:
		grcDollar = grcS[grcpt-4 : grcpt+1]
//line internal/parse/parser.y:59
		{
			grcVAL.node = N(KIf, grcDollar[2].node, grcDollar[4].node)
		}
	case 33:
		grcDollar = grcS[grcpt-8 : grcpt+1]
//line internal/parse/parser.y:61
		{
			n := N(KFor, grcDollar[3].node, grcDollar[8].node)
			if grcDollar[5].node != nil {
				n.List = grcDollar[5].node.List
			}
			grcVAL.node = n
		}
	case 34:
		grcDollar = grcS[grcpt-6 : grcpt+1]
//line internal/parse/parser.y:63
		{
			grcVAL.node = N(KFor, grcDollar[3].node, grcDollar[6].node)
		}
	case 35:
		grcDollar = grcS[grcpt-4 : grcpt+1]
//line internal/parse/parser.y:64
		{
			grcVAL.node = N(KWhile, grcDollar[2].node, grcDollar[4].node)
		}
	case 36:
		grcDollar = grcS[grcpt-8 : grcpt+1]
//line internal/parse/parser.y:66
		{
			grcVAL.node = N(KSwitch, grcDollar[3].node, grcDollar[7].node)
		}
	case 37:
		grcDollar = grcS[grcpt-4 : grcpt+1]
//line internal/parse/parser.y:67
		{
			grcVAL.node = N(KMatch, grcDollar[3].node, grcDollar[4].node)
		}
	case 38:
		grcDollar = grcS[grcpt-4 : grcpt+1]
//line internal/parse/parser.y:68
		{
			grcVAL.node = N(KAnd, grcDollar[1].node, grcDollar[4].node)
		}
	case 39:
		grcDollar = grcS[grcpt-4 : grcpt+1]
//line internal/parse/parser.y:69
		{
			grcVAL.node = N(KOr, grcDollar[1].node, grcDollar[4].node)
		}
	case 40:
		grcDollar = grcS[grcpt-4 : grcpt+1]
//line internal/parse/parser.y:70
		{
			grcVAL.node = N(KPipe, grcDollar[1].node, grcDollar[4].node)
			if grcDollar[2].node != nil {
				grcVAL.node.I1 = grcDollar[2].node.I1
				grcVAL.node.I2 = grcDollar[2].node.I2
			}
		}
	case 41:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:71
		{
			grcVAL.node = N(KPre, grcDollar[1].node, grcDollar[2].node)
		}
	case 42:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:72
		{
			grcVAL.node = N(KPre, grcDollar[1].node, grcDollar[2].node)
		}
	case 43:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:73
		{
			grcVAL.node = N(KBang, grcDollar[3].node, nil)
		}
	case 44:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:74
		{
			grcVAL.node = N(KSubshell, grcDollar[3].node, nil)
		}
	case 45:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:75
		{
			grcVAL.node = N(KFnDef, grcDollar[2].node, grcDollar[3].node)
		}
	case 46:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:76
		{
			grcVAL.node = N(KFnRm, grcDollar[2].node, nil)
		}
	case 50:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:80
		{
			grcVAL.node = L(KArgList, grcDollar[1].node, grcDollar[2].node)
		}
	case 52:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:82
		{
			grcVAL.node = L(KArgList, grcDollar[1].node, grcDollar[2].node)
		}
	case 56:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:86
		{
			grcVAL.node = N(KConcat, grcDollar[1].node, grcDollar[3].node)
		}
	case 58:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:88
		{
			grcVAL.node = grcDollar[1].node
		}
	case 60:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:90
		{
			grcVAL.node = N(KConcat, grcDollar[1].node, grcDollar[3].node)
		}
	case 61:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:91
		{
			grcVAL.node = N(KVar, grcDollar[2].node, nil)
		}
	case 62:
		grcDollar = grcS[grcpt-5 : grcpt+1]
//line internal/parse/parser.y:92
		{
			grcVAL.node = N(KVar, grcDollar[2].node, grcDollar[4].node)
		}
	case 63:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:93
		{
			grcVAL.node = N(KCount, grcDollar[2].node, nil)
		}
	case 64:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:94
		{
			grcVAL.node = N(KFlat, grcDollar[2].node, nil)
		}
	case 65:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:95
		{
			grcVAL.node = N(KBackquote, nil, grcDollar[2].node)
		}
	case 66:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:96
		{
			grcVAL.node = N(KBackquote, nil, grcDollar[2].node)
		}
	case 67:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:97
		{
			grcVAL.node = N(KBackquote, grcDollar[2].node, grcDollar[3].node)
		}
	case 68:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:98
		{
			grcVAL.node = N(KBackquote, grcDollar[2].node, grcDollar[3].node)
		}
	case 69:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:99
		{
			grcVAL.node = N(KParen, grcDollar[2].node, nil)
		}
	case 70:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:100
		{
			grcVAL.node = N(KNmpipe, grcDollar[1].node, grcDollar[2].node)
		}
	case 72:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:102
		{
			grcVAL.node = W("for")
		}
	case 73:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:103
		{
			grcVAL.node = W("in")
		}
	case 74:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:104
		{
			grcVAL.node = W("while")
		}
	case 75:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:105
		{
			grcVAL.node = W("if")
		}
	case 76:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:106
		{
			grcVAL.node = W("switch")
		}
	case 77:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:107
		{
			grcVAL.node = W("fn")
		}
	case 78:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:108
		{
			grcVAL.node = W("case")
		}
	case 79:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:109
		{
			grcVAL.node = W("~")
		}
	case 80:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:110
		{
			grcVAL.node = W("!")
		}
	case 81:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:111
		{
			grcVAL.node = W("@")
		}
	case 82:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:112
		{
			grcVAL.node = W("=")
		}
	case 83:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:113
		{
			grcVAL.node = nil
		}
	case 84:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:114
		{
			grcVAL.node = L(KWords, grcDollar[1].node, grcDollar[2].node)
		}
	case 85:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:115
		{
			grcVAL.node = nil
		}
	case 87:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:117
		{
			grcVAL.node = L(KWords, grcDollar[1].node, grcDollar[2].node)
		}
	}
	goto grcstack /* stack new state and value */
}
