// Code generated by goyacc -o internal/parse/parser.go -p grc internal/parse/parser.y. DO NOT EDIT.

//line internal/parse/parser.y:13
package parse

import __yyfmt__ "fmt"

//line internal/parse/parser.y:13

var parseResult *Node

var lastword int

//line internal/parse/parser.y:19
type grcSymType struct {
	yys  int
	node *Node
	str  string
}

const FOR = 57346
const IN = 57347
const WHILE = 57348
const IF = 57349
const NOT = 57350
const TWIDDLE = 57351
const BANG = 57352
const SUBSHELL = 57353
const SWITCH = 57354
const FN = 57355
const WORD = 57356
const REDIR = 57357
const DUP = 57358
const PIPE = 57359
const SUB = 57360
const SIMPLE = 57361
const ARGLIST = 57362
const WORDS = 57363
const BRACE = 57364
const PAREN = 57365
const PCMD = 57366
const PIPEFD = 57367
const ANDAND = 57368
const OROR = 57369
const COUNT = 57370

var grcToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"FOR",
	"IN",
	"WHILE",
	"IF",
	"NOT",
	"TWIDDLE",
	"BANG",
	"SUBSHELL",
	"SWITCH",
	"FN",
	"WORD",
	"REDIR",
	"DUP",
	"PIPE",
	"SUB",
	"SIMPLE",
	"ARGLIST",
	"WORDS",
	"BRACE",
	"PAREN",
	"PCMD",
	"PIPEFD",
	"')'",
	"ANDAND",
	"OROR",
	"'^'",
	"'$'",
	"COUNT",
	"'\"'",
	"'\\n'",
	"';'",
	"'&'",
	"'{'",
	"'}'",
	"'('",
	"'='",
	"'`'",
}

var grcStatenames = [...]string{}

const grcEofCode = 1
const grcErrCode = 2
const grcInitialStackSize = 16

//line internal/parse/parser.y:88

//line yacctab:1
var grcExca = [...]int8{
	-1, 0,
	1, 1,
	-2, 18,
	-1, 1,
	1, -1,
	-2, 0,
}

const grcPrivate = 57344

const grcLast = 323

var grcAct = [...]int8{
	21, 66, 3, 70, 65, 40, 3, 41, 92, 64,
	45, 45, 45, 69, 60, 61, 62, 63, 39, 88,
	45, 12, 35, 45, 45, 45, 17, 36, 17, 5,
	28, 88, 58, 78, 79, 80, 100, 77, 45, 99,
	82, 83, 45, 91, 86, 84, 97, 33, 40, 72,
	44, 33, 18, 43, 57, 59, 76, 101, 36, 81,
	88, 31, 32, 71, 10, 45, 73, 74, 75, 89,
	45, 45, 94, 87, 37, 20, 13, 67, 45, 38,
	1, 71, 33, 0, 0, 85, 72, 0, 42, 45,
	45, 0, 31, 32, 90, 0, 68, 4, 93, 29,
	30, 4, 0, 105, 45, 45, 2, 103, 0, 108,
	104, 34, 0, 95, 96, 46, 47, 48, 49, 50,
	51, 52, 53, 54, 55, 25, 56, 0, 0, 33,
	0, 0, 102, 0, 0, 0, 0, 107, 0, 31,
	32, 22, 24, 23, 0, 0, 29, 30, 0, 27,
	0, 26, 46, 47, 48, 49, 50, 51, 52, 53,
	54, 55, 25, 56, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 106, 0, 0, 0, 22, 24,
	23, 0, 0, 0, 0, 0, 27, 0, 26, 46,
	47, 48, 49, 50, 51, 52, 53, 54, 55, 25,
	56, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 98, 0, 0, 0, 22, 24, 23, 0, 0,
	0, 0, 0, 27, 0, 26, 46, 47, 48, 49,
	50, 51, 52, 53, 54, 55, 25, 56, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 25, 19,
	20, 0, 22, 24, 23, 0, 0, 0, 17, 0,
	27, 0, 26, 0, 22, 24, 23, 0, 0, 0,
	0, 0, 27, 7, 26, 8, 6, 0, 11, 14,
	15, 9, 16, 25, 19, 20, 46, 47, 48, 49,
	50, 51, 52, 53, 54, 55, 25, 56, 0, 22,
	24, 23, 0, 0, 0, 17, 0, 27, 0, 26,
	0, 0, 22, 24, 23, 0, 0, 0, 0, 0,
	27, 0, 26,
}

var grcPact = [...]int16{
	269, -1000, -3, 112, 269, 59, 10, -31, -33, 282,
	234, 282, 269, 269, 269, 269, -1000, 269, -26, 222,
	-1000, -1000, 282, 282, 282, -1000, -8, -1000, -1000, -1000,
	-1000, 269, 269, 269, -1000, -1000, 59, 282, 269, 269,
	269, 282, 269, -10, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -8, 2, -1000, 2,
	30, 30, 30, 30, 222, -29, 65, 269, -1000, 282,
	282, 2, -1000, 28, -1000, -1000, -1000, 185, 30, 30,
	-1000, -1000, 34, 34, 13, 31, 34, -1000, 282, 282,
	-1000, 2, -1000, -1000, -1000, 2, -1000, -1000, -1000, -1000,
	-1000, 269, -1000, 148, 111, 34, -1000, 269, 34,
}

var grcPgo = [...]int8{
	0, 80, 106, 79, 29, 4, 96, 77, 76, 22,
	21, 1, 64, 52, 43, 0, 50, 9,
}

var grcR1 = [...]int8{
	0, 1, 1, 2, 2, 5, 5, 6, 6, 7,
	7, 4, 3, 8, 9, 9, 10, 10, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 12, 12, 12,
	13, 13, 14, 14, 14, 15, 15, 15, 15, 15,
	15, 15, 15, 16, 16, 16, 16, 16, 16, 16,
	16, 16, 16, 17, 17,
}

var grcR2 = [...]int8{
	0, 0, 2, 1, 2, 1, 2, 2, 2, 1,
	2, 3, 3, 3, 0, 2, 2, 1, 0, 2,
	3, 3, 7, 5, 3, 3, 1, 3, 3, 3,
	3, 2, 2, 2, 2, 3, 2, 1, 2, 2,
	1, 3, 1, 1, 3, 2, 5, 2, 2, 1,
	2, 3, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 0, 2,
}

var grcChk = [...]int16{
	-1000, -1, -2, -11, -6, -4, 7, 4, 6, 12,
	-12, 9, -10, -8, 10, 11, 13, 36, -13, 15,
	16, -15, 30, 32, 31, 14, 40, 38, 33, 34,
	35, 27, 28, 17, -2, -9, -10, 15, -3, 8,
	38, 38, -3, -14, -16, -15, 4, 5, 6, 7,
	8, 9, 10, 11, 12, 13, 15, -14, -10, -14,
	-11, -11, -11, -11, -17, -5, -11, -7, -6, 39,
	29, -14, -4, -14, -14, -14, -4, -17, -11, -11,
	-11, -9, -11, -11, -5, -14, -11, -4, 29, -17,
	-4, -14, 37, 33, -5, -14, -14, 18, 26, 26,
	5, 26, -14, -17, -17, -11, 26, 26, -11,
}

var grcDef = [...]int8{
	-2, -2, 0, 3, 18, 14, 0, 0, 0, 0,
	26, 0, 18, 18, 18, 18, 63, 18, 37, 0,
	17, 40, 0, 0, 0, 49, 0, 63, 2, 7,
	8, 18, 18, 18, 4, 19, 14, 0, 18, 18,
	18, 0, 18, 0, 42, 43, 53, 54, 55, 56,
	57, 58, 59, 60, 61, 62, 0, 38, 39, 63,
	31, 32, 33, 34, 36, 0, 5, 18, 9, 0,
	0, 16, 52, 45, 47, 48, 50, 0, 28, 29,
	30, 15, 20, 21, 0, 0, 24, 25, 0, 27,
	35, 64, 11, 10, 6, 13, 41, 63, 51, 12,
	63, 18, 44, 0, 0, 23, 46, 18, 22,
}

var grcTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	33, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 32, 3, 30, 3, 35, 3,
	38, 26, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 34,
	3, 39, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 29, 3, 40, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 36, 3, 37,
}

var grcTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 27, 28, 31,
}

var grcTok3 = [...]int8{
	0,
}

var grcErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	grcDebug        = 0
	grcErrorVerbose = false
)

type grcLexer interface {
	Lex(lval *grcSymType) int
	Error(s string)
}

type grcParser interface {
	Parse(grcLexer) int
	Lookahead() int
}

type grcParserImpl struct {
	lval  grcSymType
	stack [grcInitialStackSize]grcSymType
	char  int
}

func (p *grcParserImpl) Lookahead() int {
	return p.char
}

func grcNewParser() grcParser {
	return &grcParserImpl{}
}

const grcFlag = -1000

func grcTokname(c int) string {
	if c >= 1 && c-1 < len(grcToknames) {
		if grcToknames[c-1] != "" {
			return grcToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func grcStatname(s int) string {
	if s >= 0 && s < len(grcStatenames) {
		if grcStatenames[s] != "" {
			return grcStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func grcErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !grcErrorVerbose {
		return "syntax error"
	}

	for _, e := range grcErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + grcTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(grcPact[state])
	for tok := TOKSTART; tok-1 < len(grcToknames); tok++ {
		if n := base + tok; n >= 0 && n < grcLast && int(grcChk[int(grcAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if grcDef[state] == -2 {
		i := 0
		for grcExca[i] != -1 || int(grcExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; grcExca[i] >= 0; i += 2 {
			tok := int(grcExca[i])
			if tok < TOKSTART || grcExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if grcExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += grcTokname(tok)
	}
	return res
}

func grclex1(lex grcLexer, lval *grcSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(grcTok1[0])
		goto out
	}
	if char < len(grcTok1) {
		token = int(grcTok1[char])
		goto out
	}
	if char >= grcPrivate {
		if char < grcPrivate+len(grcTok2) {
			token = int(grcTok2[char-grcPrivate])
			goto out
		}
	}
	for i := 0; i < len(grcTok3); i += 2 {
		token = int(grcTok3[i+0])
		if token == char {
			token = int(grcTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(grcTok2[1]) /* unknown char */
	}
	if grcDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", grcTokname(token), uint(char))
	}
	return char, token
}

func grcParse(grclex grcLexer) int {
	return grcNewParser().Parse(grclex)
}

func (grcrcvr *grcParserImpl) Parse(grclex grcLexer) int {
	var grcn int
	var grcVAL grcSymType
	var grcDollar []grcSymType
	_ = grcDollar // silence set and not used
	grcS := grcrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	grcstate := 0
	grcrcvr.char = -1
	grctoken := -1 // grcrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		grcstate = -1
		grcrcvr.char = -1
		grctoken = -1
	}()
	grcp := -1
	goto grcstack

ret0:
	return 0

ret1:
	return 1

grcstack:
	/* put a state and value onto the stack */
	if grcDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", grcTokname(grctoken), grcStatname(grcstate))
	}

	grcp++
	if grcp >= len(grcS) {
		nyys := make([]grcSymType, len(grcS)*2)
		copy(nyys, grcS)
		grcS = nyys
	}
	grcS[grcp] = grcVAL
	grcS[grcp].yys = grcstate

grcnewstate:
	grcn = int(grcPact[grcstate])
	if grcn <= grcFlag {
		goto grcdefault /* simple state */
	}
	if grcrcvr.char < 0 {
		grcrcvr.char, grctoken = grclex1(grclex, &grcrcvr.lval)
	}
	grcn += grctoken
	if grcn < 0 || grcn >= grcLast {
		goto grcdefault
	}
	grcn = int(grcAct[grcn])
	if int(grcChk[grcn]) == grctoken { /* valid shift */
		grcrcvr.char = -1
		grctoken = -1
		grcVAL = grcrcvr.lval
		grcstate = grcn
		if Errflag > 0 {
			Errflag--
		}
		goto grcstack
	}

grcdefault:
	/* default state action */
	grcn = int(grcDef[grcstate])
	if grcn == -2 {
		if grcrcvr.char < 0 {
			grcrcvr.char, grctoken = grclex1(grclex, &grcrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if grcExca[xi+0] == -1 && int(grcExca[xi+1]) == grcstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			grcn = int(grcExca[xi+0])
			if grcn < 0 || grcn == grctoken {
				break
			}
		}
		grcn = int(grcExca[xi+1])
		if grcn < 0 {
			goto ret0
		}
	}
	if grcn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			grclex.Error(grcErrorMessage(grcstate, grctoken))
			Nerrs++
			if grcDebug >= 1 {
				__yyfmt__.Printf("%s", grcStatname(grcstate))
				__yyfmt__.Printf(" saw %s\n", grcTokname(grctoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for grcp >= 0 {
				grcn = int(grcPact[grcS[grcp].yys]) + grcErrCode
				if grcn >= 0 && grcn < grcLast {
					grcstate = int(grcAct[grcn]) /* simulate a shift of "error" */
					if int(grcChk[grcstate]) == grcErrCode {
						goto grcstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if grcDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", grcS[grcp].yys)
				}
				grcp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if grcDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", grcTokname(grctoken))
			}
			if grctoken == grcEofCode {
				goto ret1
			}
			grcrcvr.char = -1
			grctoken = -1
			goto grcnewstate /* try again in the same state */
		}
	}

	/* reduction by production grcn */
	if grcDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", grcn, grcStatname(grcstate))
	}

	grcnt := grcn
	grcpt := grcp
	_ = grcpt // guard against "declared and not used"

	grcp -= int(grcR2[grcn])
	// grcp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if grcp+1 >= len(grcS) {
		nyys := make([]grcSymType, len(grcS)*2)
		copy(nyys, grcS)
		grcS = nyys
	}
	grcVAL = grcS[grcp+1]

	/* consult goto table to find next state */
	grcn = int(grcR1[grcn])
	grcg := int(grcPgo[grcn])
	grcj := grcg + grcS[grcp].yys + 1

	if grcj >= grcLast {
		grcstate = int(grcAct[grcg])
	} else {
		grcstate = int(grcAct[grcj])
		if int(grcChk[grcstate]) != -grcn {
			grcstate = int(grcAct[grcg])
		}
	}
	// dummy call; replaced with literal code
	switch grcnt {

	case 1:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:28
		{
			return 1
		}
	case 2:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:29
		{
			grcVAL.node = grcDollar[1].node
			parseResult = grcVAL.node
			return 1
		}
	case 4:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:31
		{
			grcVAL.node = N(KSeq, grcDollar[1].node, grcDollar[2].node)
		}
	case 6:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:33
		{
			grcVAL.node = N(KSeq, grcDollar[1].node, grcDollar[2].node)
		}
	case 7:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:34
		{
			grcVAL.node = grcDollar[1].node
		}
	case 8:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:35
		{
			grcVAL.node = N(KBg, grcDollar[1].node, nil)
		}
	case 10:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:37
		{
			grcVAL.node = grcDollar[1].node
		}
	case 11:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:38
		{
			grcVAL.node = N(KBrace, grcDollar[2].node, nil)
		}
	case 12:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:39
		{
			grcVAL.node = N(KParen, grcDollar[2].node, nil)
		}
	case 13:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:40
		{
			grcVAL.node = N(KAssign, grcDollar[1].node, grcDollar[3].node)
		}
	case 14:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:41
		{
			grcVAL.node = nil
		}
	case 15:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:42
		{
			grcVAL.node = L(KRedir, grcDollar[1].node, grcDollar[2].node)
		}
	case 16:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:43
		{
			grcVAL.node = N(KRedir, grcDollar[1].node, grcDollar[2].node)
		}
	case 17:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:44
		{
			grcVAL.node = grcDollar[1].node
		}
	case 18:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:45
		{
			grcVAL.node = nil
		}
	case 19:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:46
		{
			grcVAL.node = N(KCall, grcDollar[1].node, grcDollar[2].node)
		}
	case 20:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:48
		{
			grcVAL.node = N(Kind(IF), grcDollar[2].node, grcDollar[3].node)
		}
	case 21:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:49
		{
			grcVAL.node = N(Kind(IF), grcDollar[2].node, grcDollar[3].node)
		}
	case 22:
		grcDollar = grcS[grcpt-7 : grcpt+1]
//line internal/parse/parser.y:51
		{
			grcVAL.node = N(Kind(FOR), L(KWords, grcDollar[3].node, grcDollar[5].node), grcDollar[7].node)
		}
	case 23:
		grcDollar = grcS[grcpt-5 : grcpt+1]
//line internal/parse/parser.y:53
		{
			grcVAL.node = N(Kind(FOR), grcDollar[3].node, grcDollar[5].node)
		}
	case 24:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:55
		{
			grcVAL.node = N(Kind(WHILE), grcDollar[2].node, grcDollar[3].node)
		}
	case 25:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:57
		{
			grcVAL.node = N(KSwitch, grcDollar[2].node, grcDollar[3].node)
		}
	case 26:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:58
		{
			grcVAL.node = N(KCall, grcDollar[1].node, nil)
		}
	case 27:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:59
		{
			grcVAL.node = N(Kind(TWIDDLE), grcDollar[2].node, grcDollar[3].node)
		}
	case 28:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:60
		{
			grcVAL.node = N(KAnd, grcDollar[1].node, grcDollar[3].node)
		}
	case 29:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:61
		{
			grcVAL.node = N(KOr, grcDollar[1].node, grcDollar[3].node)
		}
	case 30:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:62
		{
			grcVAL.node = N(KPipe, grcDollar[1].node, grcDollar[3].node)
		}
	case 31:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:63
		{
			grcVAL.node = N(KRedir, grcDollar[1].node, grcDollar[2].node)
		}
	case 32:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:64
		{
			grcVAL.node = N(KAssign, grcDollar[1].node, grcDollar[2].node)
		}
	case 33:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:65
		{
			grcVAL.node = N(Kind(BANG), grcDollar[2].node, nil)
		}
	case 34:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:66
		{
			grcVAL.node = N(KSubshell, grcDollar[2].node, nil)
		}
	case 35:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:67
		{
			grcVAL.node = N(KFnDef, grcDollar[2].node, grcDollar[3].node)
		}
	case 36:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:68
		{
			grcVAL.node = N(KFn, grcDollar[2].node, nil)
		}
	case 38:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:70
		{
			grcVAL.node = L(KArgList, grcDollar[1].node, grcDollar[2].node)
		}
	case 39:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:71
		{
			grcVAL.node = L(KArgList, grcDollar[1].node, grcDollar[2].node)
		}
	case 41:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:73
		{
			grcVAL.node = N(Kind('^'), grcDollar[1].node, grcDollar[3].node)
		}
	case 42:
		grcDollar = grcS[grcpt-1 : grcpt+1]
//line internal/parse/parser.y:74
		{
			lastword = 1
			grcVAL.node = grcDollar[1].node
			if grcVAL.node != nil {
				grcVAL.node.Kind = KWord
			}
		}
	case 44:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:76
		{
			grcVAL.node = N(Kind('^'), grcDollar[1].node, grcDollar[3].node)
		}
	case 45:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:77
		{
			grcVAL.node = N(KDollar, grcDollar[2].node, nil)
		}
	case 46:
		grcDollar = grcS[grcpt-5 : grcpt+1]
//line internal/parse/parser.y:78
		{
			grcVAL.node = N(KSub, grcDollar[2].node, grcDollar[4].node)
		}
	case 47:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:79
		{
			grcVAL.node = N(KQuote, grcDollar[2].node, nil)
		}
	case 48:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:80
		{
			grcVAL.node = N(KCount, grcDollar[2].node, nil)
		}
	case 50:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:82
		{
			grcVAL.node = N(KBackquote, grcDollar[2].node, nil)
		}
	case 51:
		grcDollar = grcS[grcpt-3 : grcpt+1]
//line internal/parse/parser.y:83
		{
			grcVAL.node = N(KParen, grcDollar[2].node, nil)
		}
	case 52:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:84
		{
			grcVAL.node = N(KRedir, grcDollar[1].node, grcDollar[2].node)
		}
	case 63:
		grcDollar = grcS[grcpt-0 : grcpt+1]
//line internal/parse/parser.y:86
		{
			grcVAL.node = nil
		}
	case 64:
		grcDollar = grcS[grcpt-2 : grcpt+1]
//line internal/parse/parser.y:87
		{
			grcVAL.node = L(KWords, grcDollar[1].node, grcDollar[2].node)
		}
	}
	goto grcstack /* stack new state and value */
}
